// This file contains the database schema types for Supabase

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          address: Json | null;
          role: 'customer' | 'vendor' | 'admin';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          address?: Json | null;
          role?: 'customer' | 'vendor' | 'admin';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          address?: Json | null;
          role?: 'customer' | 'vendor' | 'admin';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      vendors: {
        Row: {
          id: string;
          user_id: string;
          store_name: string;
          store_slug: string;
          store_description: string | null;
          store_logo: string | null;
          store_banner: string | null;
          business_email: string | null;
          business_phone: string | null;
          business_address: Json | null;
          commission_rate: number;
          is_verified: boolean;
          is_active: boolean;
          total_sales: number;
          total_revenue: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          store_name: string;
          store_slug: string;
          store_description?: string | null;
          store_logo?: string | null;
          store_banner?: string | null;
          business_email?: string | null;
          business_phone?: string | null;
          business_address?: Json | null;
          commission_rate?: number;
          is_verified?: boolean;
          is_active?: boolean;
          total_sales?: number;
          total_revenue?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          store_name?: string;
          store_slug?: string;
          store_description?: string | null;
          store_logo?: string | null;
          store_banner?: string | null;
          business_email?: string | null;
          business_phone?: string | null;
          business_address?: Json | null;
          commission_rate?: number;
          is_verified?: boolean;
          is_active?: boolean;
          total_sales?: number;
          total_revenue?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          parent_id: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          vendor_id: string;
          category_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          short_description: string | null;
          price: number;
          compare_at_price: number | null;
          cost_price: number | null;
          sku: string | null;
          barcode: string | null;
          inventory_quantity: number;
          inventory_policy: 'allow' | 'deny';
          weight: number | null;
          dimensions: Json | null;
          images: string[];
          featured_image: string | null;
          attributes: Json;
          tags: string[];
          rating: number;
          review_count: number;
          total_sales: number;
          is_featured: boolean;
          is_active: boolean;
          seo_title: string | null;
          seo_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vendor_id: string;
          category_id?: string | null;
          name: string;
          slug: string;
          description?: string | null;
          short_description?: string | null;
          price: number;
          compare_at_price?: number | null;
          cost_price?: number | null;
          sku?: string | null;
          barcode?: string | null;
          inventory_quantity?: number;
          inventory_policy?: 'allow' | 'deny';
          weight?: number | null;
          dimensions?: Json | null;
          images?: string[];
          featured_image?: string | null;
          attributes?: Json;
          tags?: string[];
          rating?: number;
          review_count?: number;
          total_sales?: number;
          is_featured?: boolean;
          is_active?: boolean;
          seo_title?: string | null;
          seo_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vendor_id?: string;
          category_id?: string | null;
          name?: string;
          slug?: string;
          description?: string | null;
          short_description?: string | null;
          price?: number;
          compare_at_price?: number | null;
          cost_price?: number | null;
          sku?: string | null;
          barcode?: string | null;
          inventory_quantity?: number;
          inventory_policy?: 'allow' | 'deny';
          weight?: number | null;
          dimensions?: Json | null;
          images?: string[];
          featured_image?: string | null;
          attributes?: Json;
          tags?: string[];
          rating?: number;
          review_count?: number;
          total_sales?: number;
          is_featured?: boolean;
          is_active?: boolean;
          seo_title?: string | null;
          seo_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          product_id: string;
          user_id: string;
          order_id: string | null;
          rating: number;
          title: string | null;
          content: string | null;
          is_verified_purchase: boolean;
          helpful_count: number;
          is_approved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          user_id: string;
          order_id?: string | null;
          rating: number;
          title?: string | null;
          content?: string | null;
          is_verified_purchase?: boolean;
          helpful_count?: number;
          is_approved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          user_id?: string;
          order_id?: string | null;
          rating?: number;
          title?: string | null;
          content?: string | null;
          is_verified_purchase?: boolean;
          helpful_count?: number;
          is_approved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string | null;
          status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
          payment_status: 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded';
          fulfillment_status: 'unfulfilled' | 'partial' | 'fulfilled';
          currency: string;
          subtotal: number;
          tax_amount: number;
          shipping_amount: number;
          discount_amount: number;
          total_amount: number;
          shipping_address: Json | null;
          billing_address: Json | null;
          customer_email: string | null;
          customer_phone: string | null;
          customer_name: string | null;
          notes: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number: string;
          user_id?: string | null;
          status?: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
          payment_status?: 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded';
          fulfillment_status?: 'unfulfilled' | 'partial' | 'fulfilled';
          currency?: string;
          subtotal: number;
          tax_amount?: number;
          shipping_amount?: number;
          discount_amount?: number;
          total_amount: number;
          shipping_address?: Json | null;
          billing_address?: Json | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          customer_name?: string | null;
          notes?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          user_id?: string | null;
          status?: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
          payment_status?: 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded';
          fulfillment_status?: 'unfulfilled' | 'partial' | 'fulfilled';
          currency?: string;
          subtotal?: number;
          tax_amount?: number;
          shipping_amount?: number;
          discount_amount?: number;
          total_amount?: number;
          shipping_address?: Json | null;
          billing_address?: Json | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          customer_name?: string | null;
          notes?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          stripe_subscription_id: string | null;
          stripe_customer_id: string | null;
          plan_type: 'basic' | 'premium' | 'enterprise';
          status: 'active' | 'cancelled' | 'past_due' | 'unpaid' | 'paused';
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          plan_type: 'basic' | 'premium' | 'enterprise';
          status?: 'active' | 'cancelled' | 'past_due' | 'unpaid' | 'paused';
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          plan_type?: 'basic' | 'premium' | 'enterprise';
          status?: 'active' | 'cancelled' | 'past_due' | 'unpaid' | 'paused';
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
